
services:
  notification-database:
    image: postgres:17.5
    container_name: notification-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: notification_db
    volumes:
      - notification_postgres_data:/var/lib/postgresql/data
    ports:
      - ":5432"
    networks:
      - notification_net

  notification-redis:
    image: redis:8.0
    container_name: notification-redis
    restart: unless-stopped
    volumes:
      - notification_redis_data:/data
    ports:
      - ":6379"
    networks:
      - notification_net

  notification-service:
    build:
      context: notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://user:pass1234@notification-database:5432/notification_db
      REDIS_URL: redis://notification-redis:6379
      RABBITMQ_URL: amqp://user:pass1234@rabbitmq:5672
    depends_on:
      - notification-database
      - notification-redis
    networks:
      - notification_net
      - queue_net
    ports:
      - "3001:3000"


networks:
  notification_net:
    name: notification_net
    driver: bridge

  queue_net:
    external: true

volumes:
  notification_postgres_data:
  notification_redis_data:
  notification_rabbitmq_data:

