services:
  rabbitmq:
    image: rabbitmq:4.1
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass1234
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - queue_data:/var/lib/rabbitmq
    networks:
      - queue_net

volumes:
  queue_data:

networks:
  queue_net:
    external: true
