
services:
  payment-database:
    image: postgres:17.5
    container_name: payment-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
      POSTGRES_DB: payment_db
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data
    ports:
      - ":5432"
    networks:
      - payment_net

  payment-service:
    build:
      context: payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    restart: unless-stopped
    depends_on:
      - payment-database
    networks:
      - payment_net
      - queue_net
    ports:
      - "3000:3000"

networks:
  payment_net:
    name: payment_net
    driver: bridge

  queue_net:
    external: true

volumes:
  payment_postgres_data:
